import { CurrencyInfo } from '../types';

export const CURRENCY_DATA: Record<string, CurrencyInfo> = {
  USD: { name: 'US Dollar', flag: 'us' },
  THB: { name: 'Thai Baht', flag: 'th' },
  EUR: { name: 'Euro', flag: 'eu' },
  JPY: { name: 'Japanese Yen', flag: 'jp' },
  GBP: { name: 'British Pound', flag: 'gb' },
  AUD: { name: 'Australian Dollar', flag: 'au' },
  CAD: { name: 'Canadian Dollar', flag: 'ca' },
  CHF: { name: 'Swiss Franc', flag: 'ch' },
  CNY: { name: 'Chinese Renminbi', flag: 'cn' },
  SGD: { name: 'Singapore Dollar', flag: 'sg' },
  HKD: { name: 'Hong Kong Dollar', flag: 'hk' },
  KRW: { name: 'South Korean Won', flag: 'kr' },
  TWD: { name: 'New Taiwan Dollar', flag: 'tw' },
  MYR: { name: 'Malaysian Ringgit', flag: 'my' },
  VND: { name: 'Vietnamese Dong', flag: 'vn' },
  IDR: { name: 'Indonesian Rupiah', flag: 'id' },
  PHP: { name: 'Philippine Peso', flag: 'ph' },
  INR: { name: 'Indian Rupee', flag: 'in' },
  AED: { name: 'UAE Dirham', flag: 'ae' },
  NZD: { name: 'New Zealand Dollar', flag: 'nz' },
  AFN: { name: 'Afghan Afghani', flag: 'af' },
  ALL: { name: 'Albanian Lek', flag: 'al' },
  AMD: { name: 'Armenian Dram', flag: 'am' },
  ANG: { name: 'Neth. Antillean Guilder', flag: 'an' },
  AOA: { name: 'Angolan Kwanza', flag: 'ao' },
  ARS: { name: 'Argentine Peso', flag: 'ar' },
  AWG: { name: 'Aruban Florin', flag: 'aw' },
  AZN: { name: 'Azerbaijani Manat', flag: 'az' },
  BAM: { name: 'Bosnia-Herzegovina Mark', flag: 'ba' },
  BBD: { name: 'Barbadian Dollar', flag: 'bb' },
  BDT: { name: 'Bangladeshi Taka', flag: 'bd' },
  BGN: { name: 'Bulgarian Lev', flag: 'bg' },
  BHD: { name: 'Bahraini Dinar', flag: 'bh' },
  BIF: { name: 'Burundian Franc', flag: 'bi' },
  BMD: { name: 'Bermudian Dollar', flag: 'bm' },
  BND: { name: 'Brunei Dollar', flag: 'bn' },
  BOB: { name: 'Bolivian Boliviano', flag: 'bo' },
  BRL: { name: 'Brazilian Real', flag: 'br' },
  BSD: { name: 'Bahamian Dollar', flag: 'bs' },
  BTN: { name: 'Bhutanese Ngultrum', flag: 'bt' },
  BWP: { name: 'Botswanan Pula', flag: 'bw' },
  BYN: { name: 'Belarusian Ruble', flag: 'by' },
  BZD: { name: 'Belize Dollar', flag: 'bz' },
  CDF: { name: 'Congolese Franc', flag: 'cd' },
  CLP: { name: 'Chilean Peso', flag: 'cl' },
  COP: { name: 'Colombian Peso', flag: 'co' },
  CRC: { name: 'Costa Rican Colón', flag: 'cr' },
  CUP: { name: 'Cuban Peso', flag: 'cu' },
  CVE: { name: 'Cape Verdean Escudo', flag: 'cv' },
  CZK: { name: 'Czech Koruna', flag: 'cz' },
  DJF: { name: 'Djiboutian Franc', flag: 'dj' },
  DKK: { name: 'Danish Krone', flag: 'dk' },
  DOP: { name: 'Dominican Peso', flag: 'do' },
  DZD: { name: 'Algerian Dinar', flag: 'dz' },
  EGP: { name: 'Egyptian Pound', flag: 'eg' },
  ERN: { name: 'Eritrean Nakfa', flag: 'er' },
  ETB: { name: 'Ethiopian Birr', flag: 'et' },
  FJD: { name: 'Fijian Dollar', flag: 'fj' },
  FKP: { name: 'Falkland Islands Pound', flag: 'fk' },
  FOK: { name: 'Faroese Króna', flag: 'fo' },
  GEL: { name: 'Georgian Lari', flag: 'ge' },
  GGP: { name: 'Guernsey Pound', flag: 'gg' },
  GHS: { name: 'Ghanaian Cedi', flag: 'gh' },
  GIP: { name: 'Gibraltar Pound', flag: 'gi' },
  GMD: { name: 'Gambian Dalasi', flag: 'gm' },
  GNF: { name: 'Guinean Franc', flag: 'gn' },
  GTQ: { name: 'Guatemalan Quetzal', flag: 'gt' },
  GYD: { name: 'Guyanese Dollar', flag: 'gy' },
  HNL: { name: 'Honduran Lempira', flag: 'hn' },
  HRK: { name: 'Croatian Kuna', flag: 'hr' },
  HTG: { name: 'Haitian Gourde', flag: 'ht' },
  HUF: { name: 'Hungarian Forint', flag: 'hu' },
  ILS: { name: 'Israeli New Shekel', flag: 'il' },
  IMP: { name: 'Isle of Man Pound', flag: 'im' },
  IQD: { name: 'Iraqi Dinar', flag: 'iq' },
  IRR: { name: 'Iranian Rial', flag: 'ir' },
  ISK: { name: 'Icelandic Króna', flag: 'is' },
  JEP: { name: 'Jersey Pound', flag: 'je' },
  JMD: { name: 'Jamaican Dollar', flag: 'jm' },
  JOD: { name: 'Jordanian Dinar', flag: 'jo' },
  KES: { name: 'Kenyan Shilling', flag: 'ke' },
  KGS: { name: 'Kyrgystani Som', flag: 'kg' },
  KHR: { name: 'Cambodian Riel', flag: 'kh' },
  KID: { name: 'Kiribati Dollar', flag: 'ki' },
  KMF: { name: 'Comorian Franc', flag: 'km' },
  KWD: { name: 'Kuwaiti Dinar', flag: 'kw' },
  KYD: { name: 'Cayman Islands Dollar', flag: 'ky' },
  KZT: { name: 'Kazakhstani Tenge', flag: 'kz' },
  LAK: { name: 'Laotian Kip', flag: 'la' },
  LBP: { name: 'Lebanese Pound', flag: 'lb' },
  LKR: { name: 'Sri Lankan Rupee', flag: 'lk' },
  LRD: { name: 'Liberian Dollar', flag: 'lr' },
  LSL: { name: 'Lesotho Loti', flag: 'ls' },
  LYD: { name: 'Libyan Dinar', flag: 'ly' },
  MAD: { name: 'Moroccan Dirham', flag: 'ma' },
  MDL: { name: 'Moldovan Leu', flag: 'md' },
  MGA: { name: 'Malagasy Ariary', flag: 'mg' },
  MKD: { name: 'Macedonian Denar', flag: 'mk' },
  MMK: { name: 'Myanmar Kyat', flag: 'mm' },
  MNT: { name: 'Mongolian Tögrög', flag: 'mn' },
  MOP: { name: 'Macanese Pataca', flag: 'mo' },
  MRU: { name: 'Mauritanian Ouguiya', flag: 'mr' },
  MUR: { name: 'Mauritian Rupee', flag: 'mu' },
  MVR: { name: 'Maldivian Rufiyaa', flag: 'mv' },
  MWK: { name: 'Malawian Kwacha', flag: 'mw' },
  MXN: { name: 'Mexican Peso', flag: 'mx' },
  MZN: { name: 'Mozambican Metical', flag: 'mz' },
  NAD: { name: 'Namibian Dollar', flag: 'na' },
  NGN: { name: 'Nigerian Naira', flag: 'ng' },
  NIO: { name: 'Nicaraguan Córdoba', flag: 'ni' },
  NOK: { name: 'Norwegian Krone', flag: 'no' },
  NPR: { name: 'Nepalese Rupee', flag: 'np' },
  OMR: { name: 'Omani Rial', flag: 'om' },
  PAB: { name: 'Panamanian Balboa', flag: 'pa' },
  PEN: { name: 'Peruvian Sol', flag: 'pe' },
  PGK: { name: 'Papua New Guinean Kina', flag: 'pg' },
  PKR: { name: 'Pakistani Rupee', flag: 'pk' },
  PLN: { name: 'Polish Złoty', flag: 'pl' },
  PYG: { name: 'Paraguayan Guarani', flag: 'py' },
  QAR: { name: 'Qatari Riyal', flag: 'qa' },
  RON: { name: 'Romanian Leu', flag: 'ro' },
  RSD: { name: 'Serbian Dinar', flag: 'rs' },
  RUB: { name: 'Russian Ruble', flag: 'ru' },
  RWF: { name: 'Rwandan Franc', flag: 'rw' },
  SAR: { name: 'Saudi Riyal', flag: 'sa' },
  SBD: { name: 'Solomon Islands Dollar', flag: 'sb' },
  SCR: { name: 'Seychellois Rupee', flag: 'sc' },
  SDG: { name: 'Sudanese Pound', flag: 'sd' },
  SEK: { name: 'Swedish Krone', flag: 'se' },
  SHP: { name: 'St. Helena Pound', flag: 'sh' },
  SLE: { name: 'Sierra Leonean Leone', flag: 'sl' },
  SLL: { name: 'Sierra Leonean Leone', flag: 'sl' },
  SOS: { name: 'Somali Shilling', flag: 'so' },
  SRD: { name: 'Surinamese Dollar', flag: 'sr' },
  SSP: { name: 'South Sudanese Pound', flag: 'ss' },
  STN: { name: 'São Tomé Dobra', flag: 'st' },
  SYP: { name: 'Syrian Pound', flag: 'sy' },
  SZL: { name: 'Swazi Lilangeni', flag: 'sz' },
  TJS: { name: 'Tajikistani Somoni', flag: 'tj' },
  TMT: { name: 'Turkmenistani Manat', flag: 'tm' },
  TND: { name: 'Tunisian Dinar', flag: 'tn' },
  TOP: { name: 'Tongan Paʻanga', flag: 'to' },
  TRY: { name: 'Turkish Lira', flag: 'tr' },
  TTD: { name: 'Trinidad Dollar', flag: 'tt' },
  TVD: { name: 'Tuvaluan Dollar', flag: 'tv' },
  TZS: { name: 'Tanzanian Shilling', flag: 'tz' },
  UAH: { name: 'Ukrainian Hryvnia', flag: 'ua' },
  UGX: { name: 'Ugandan Shilling', flag: 'ug' },
  UYU: { name: 'Uruguayan Peso', flag: 'uy' },
  UZS: { name: 'Uzbekistani Som', flag: 'uz' },
  VES: { name: 'Venezuelan Bolívar', flag: 've' },
  VUV: { name: 'Vanuatu Vatu', flag: 'vu' },
  WST: { name: 'Samoan Tala', flag: 'ws' },
  XAF: { name: 'CFA Franc BEAC', flag: 'cf' },
  XCD: { name: 'East Caribbean Dollar', flag: 'dm' },
  XOF: { name: 'CFA Franc BCEAO', flag: 'sn' },
  XPF: { name: 'CFP Franc', flag: 'pf' },
  YER: { name: 'Yemeni Rial', flag: 'ye' },
  ZAR: { name: 'South African Rand', flag: 'za' },
  ZMW: { name: 'Zambian Kwacha', flag: 'zm' },
  ZWL: { name: 'Zimbabwean Dollar', flag: 'zw' },
  BTC: { name: 'Bitcoin', isCrypto: true, icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/btc.png' },
  ETH: { name: 'Ethereum', isCrypto: true, icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/eth.png' },
  SOL: { name: 'Solana', isCrypto: true, icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/sol.png' },
  BNB: { name: 'BNB', isCrypto: true, icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/bnb.png' },
  XRP: { name: 'XRP', isCrypto: true, icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/xrp.png' },
  ADA: { name: 'Cardano', isCrypto: true, icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/ada.png' },
  DOGE: { name: 'Dogecoin', isCrypto: true, icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/doge.png' },
  DOT: { name: 'Polkadot', isCrypto: true, icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/dot.png' },
  MATIC: { name: 'Polygon', isCrypto: true, icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/matic.png' },
  LINK: { name: 'Chainlink', isCrypto: true, icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/link.png' },
  UNI: { name: 'Uniswap', isCrypto: true, icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/uni.png' },
  LTC: { name: 'Litecoin', isCrypto: true, icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/ltc.png' },
  SHIB: { name: 'Shiba Inu', isCrypto: true, icon: 'https://cryptologos.cc/logos/shiba-inu-shib-logo.png' },
  AVAX: { name: 'Avalanche', isCrypto: true, icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/avax.png' },
  TRX: { name: 'TRON', isCrypto: true, icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/trx.png' },
  FIGR_HELOC: { name: 'Figure HELOC', isCrypto: true, icon: 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png' }
};
